### ISSUE TITLE
Баг с воротами на базе

### ISSUE THREAD

**Issue by ElektroKILLER** [bsnext/MTA-Project-Zero#38]
Кидает под текстуры из за ворот

**Воспроизведение.**
Когда открываешь ворота и закрываешь возле себя тебя кидает под текстуру

**Последствия.**
ты находишься в ней и ничего не можешь сделать,тп нельзя сделать так как на территории строительства,только самоубийство с потерей лута так как ты не сможешь его забрать

**Comment by eugene27r** [comment]
* Нужно находится на месте закрытой воротины при её закрытии.
* Персонаж проваливается в текстуру фундамента, на котором установлена воротина. 
* Воспользоваться F7 нельзя, так как персонаж находится на территории базы.
