### ISSUE TITLE
Glitch witch guns.

### ISSUE THREAD

**Issue by Huba013** [bsnext/MTA-Project-Zero#47]
**What happen**
Can shoot when u haven't ammo.

**How do it?**
First must found gun take in hand and fast click(spam left ctrl,left button on mause) (2 button witch can shoot in MTA) and your gun have -1 ammo and can hit with gun, looks like in axe.

**Can see this glitch on this film and screenshot:**
https://youtu.be/pw8LmXwYCZU

![mta-screen_2019-12-15_00-11-41](https://user-images.githubusercontent.com/58894543/70925828-3949a900-202c-11ea-83cd-363bb490e537.png)

![mta-screen_2019-12-15_00-11-40](https://user-images.githubusercontent.com/58894543/70925837-3d75c680-202c-11ea-8f57-d048df38794e.png)

**Concat**
Discord- #8955Huba013

**Found**Huba013

**Comment by salwador** [comment]
Should be fixed, need test and approve.
