### ISSUE TITLE
glitched ammo 

### ISSUE THREAD

**Issue by BigShaQ1337** [bsnext/MTA-Project-Zero#64]
What happen
you have infinite ammo

How do it?
when you grab a gun to your gun belt and click 1 and fast lpm you shoot at 3/4 ammo and when you click 1 again it gives you the ammo you fired

Can see in this film:
https://youtu.be/NMFkfD2XbLY

Concat
Discord- Król Maciuś#0959

Nickname: [GROM]BigShaQ

Can I get a reward for it? If so, I have and more bugs.

**Comment by BigShaQ1337** [comment]
@salwador  can u do something ? :>

**Comment by salwador** [comment]
Should be fixed, need test and approve.
