### ISSUE TITLE
Glitched Wall of Gate.

### ISSUE THREAD

**Issue by Huba013** [bsnext/MTA-Project-Zero#65]
**Describe the bug**
Can't put gate in gate for wall

**To Reproduce**

I craft gate for wall
I put x3 gate for wall around in 1 floor
I put x2 gate in gate for wall 
I can't put last gate in gate for wall.

**Expected behavior**
Maybe admin join in server, destroy wall for gate and gate, give me 1 more items (gate...) and i put this with large gaps.

**Screenshots or videos**
![mta-screen_2020-12-25_13-15-54](https://user-images.githubusercontent.com/58894543/103134699-67d47800-46b3-11eb-9f01-94e715aae259.png)
![mta-screen_2020-12-25_13-15-55](https://user-images.githubusercontent.com/58894543/103134701-699e3b80-46b3-11eb-8744-ac36734ea570.png)

**Concat**
Discord: Huba013#8955
Vk.com: https://vk.com/id582318353

**Comment by salwador** [comment]
Should be fixed, need test and approve.
