### ISSUE TITLE
Glitched place on floor

### ISSUE THREAD

**Issue by Huba013** [bsnext/MTA-Project-Zero#66]
**Describe the bug**
Can't put fundation / floor

**To Reproduce**
1. I craft fundation / floor
2. I want craft fance around my base
3. I can't put in this place floor.

**Expected behavior**
Maybe admin can repair this place or join and place floor.

**Screenshots or videos**
video:
https://youtu.be/DMBuVBBBOjc

**Feedback**
Discord: Huba013#8955
Vk.com: https://vk.com/id582318353

**Comment by salwador** [comment]
Should be fixed, need test and approve.
